using System.Collections.Generic;
using System.Reflection;
using UnityEngine;

public static class ConfigDataExporter
{
    /// <summary>
    /// 导出配置数据列表到CSV字符串
    /// </summary>
    public static CsvStringWriter ExportToCsvString<T>(List<T> configList, bool includeHeaders = true) where T : LocalConfigDataBase
    {
        CsvStringWriter writer = new CsvStringWriter();

        // 写入注释头
        writer.WriteCommentLine("Generated by Config System");
        writer.WriteCommentLine($"Export Time: {System.DateTime.Now}");
        writer.WriteEmptyLine();

        if (includeHeaders)
        {
            WriteHeaders<T>(writer);
        }

        WriteDataRows(configList, writer);

        return writer;
    }

    /// <summary>
    /// 导出配置数据到文件（编辑器使用）
    /// </summary>
    public static void ExportToCsvFile<T>(List<T> configList, string filePath, bool includeHeaders = true) where T : LocalConfigDataBase
    {
        CsvStreamWriter writer = new CsvStreamWriter(filePath, System.Text.Encoding.UTF8);

        writer.WriteCommentLine("Generated by Config System");
        writer.WriteCommentLine($"Export Time: {System.DateTime.Now}");
        writer.WriteEmptyLine();

        if (includeHeaders)
        {
            WriteHeaders<T>(writer);
        }

        WriteDataRows(configList, writer);

        writer.Close();
        Debug.Log($"配置数据已导出到: {filePath}");
    }

    /// <summary>
    /// 写入CSV头部（字段名和类型）
    /// </summary>
    public static void WriteHeaders<T>(ICsvWriter writer) where T : LocalConfigDataBase
    {
        FieldInfo[] fields = typeof(T).GetFields(BindingFlags.Public | BindingFlags.Instance);

        // 写入类型行
        writer.BeginNewLine();
        foreach (FieldInfo field in fields)
        {
            writer.AddField(GetTypeString(field.FieldType));
        }
        writer.BeginNewLine(); // 结束当前行

        // 写入字段名行
        writer.BeginNewLine();
        foreach (FieldInfo field in fields)
        {
            writer.AddField(field.Name);
        }
        writer.BeginNewLine(); // 结束当前行
    }

    /// <summary>
    /// 写入数据行
    /// </summary>
    public static void WriteDataRows<T>(List<T> configList, ICsvWriter writer) where T : LocalConfigDataBase
    {
        FieldInfo[] fields = typeof(T).GetFields(BindingFlags.Public | BindingFlags.Instance);

        foreach (T config in configList)
        {
            writer.BeginNewLine();
            foreach (FieldInfo field in fields)
            {
                object value = field.GetValue(config);
                writer.AddField(value);
            }
            writer.BeginNewLine(); // 结束当前行
        }
    }

    /// <summary>
    /// 获取类型字符串（匹配你的CSV格式）
    /// </summary>
    private static string GetTypeString(System.Type type)
    {
        if (type == typeof(int)) return "int";
        if (type == typeof(float)) return "float";
        if (type == typeof(string)) return "string";
        if (type == typeof(long)) return "long";
        if (type == typeof(bool)) return "bool";
        return "string"; // 默认
    }
}